# Generated by Django 5.2.5 on 2025-08-25 19:40

import birthday.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, upload_to='birthdays_images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.DateField(help_text='Обязательное поле', validators=[birthday.validators.real_age], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='first_name',
            field=models.CharField(help_text='Обязательное поле', max_length=20, verbose_name='Имя'),
        ),
        migrations.AddConstraint(
            model_name='birthday',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birthday'), name='unique person constraint'),
        ),
    ]
