# Generated by Django 5.2.5 on 2025-08-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_alter_birthday_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, default='birthdays_images/deffault_user.jpg', upload_to='birthdays_images', verbose_name='Фото'),
        ),
    ]
