# Generated by Django 5.2.5 on 2025-08-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_alter_birthday_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, upload_to='birthdays_images', verbose_name='Фото'),
        ),
    ]
